[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Cấu hình xung nhịp & Nạp code qua USB
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 115200

; BẬT DUNG LƯỢNG 8MB PSRAM (R8) VÀ 16MB FLASH (N16)
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Thư viện sử dụng cho dự án Aegis Sight
lib_deps = 
    esphome/ESP32-audioI2S
    bblanchon/ArduinoJson
    links2004/WebSockets
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO