[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
monitor_speed = 2000000

; PSRAM (8MB OPI) + Flash (16MB)
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

; Build flags
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_ESP32S3_DATA_CACHE_64KB=y
    -DCONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
    -DCONFIG_ESP32S3_INSTRUCTION_CACHE_32KB=y   

; Libraries
lib_deps = 
    esphome/ESP32-audioI2S
    bblanchon/ArduinoJson
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    tzapu/WiFiManager
    earlephilhower/ESP8266Audio @ 1.9.9
